language: java

addons:
  sonarcloud:
    organization: "mimi-siku-github"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
