language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - mvn sonar:sonar -Dsonar.projectKey=Mimi-Siku_TESTSONAR -Dsonar.organization=mimi-siku-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=3084049ee5548aad3cfcea9f2b8326155995ba32
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
